server:
  port: 8080

spring:
 application:    name: linx-teste
    
 profiles:    active:    - dev
    
 datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_linx
    username: postgres
    password: postgres
 jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    
logging:
  level:
    org.springframework: info
    org.hibernate: debug
    
